### ISSUE TITLE
Massive lag that ramps after playing

### ISSUE THREAD

**Issue by Dragonsouled** [mrsterner/voidbound#1]
My FPS is normally around 120 fps.

I found a bunch of crimson cultists around an altar and it seems like my FPS goes from 120 to (60-80) after that chunk is loaded, even if I set render/simulation distance really low and go far away from it.

I think there was also a random fire caused by lava near the area (was a JG biome with lots of burnable blocks) that exacerbated the problem and caused my FPS to drop to 30 but still very odd for my FPS to drop so much, I wouldn't expect fire to do that.

Cultists in question
![2024-09-08_15 51 34](https://github.com/user-attachments/assets/c5fba2e6-0467-4397-800b-f6ed227f28fb)

Edit: Worth noting that when I first relaunched world, lag went away temporarily but now when I do it I spawn with lag, and that disabling the fire tick gamerule doesn't improve lag.

**Comment by PinkDisorder** [comment]
With a 13700K and a 4070 ti super, my fps dropped to 20 and eventually the game crashed, taking windows explorer with it.

**Comment by Schwantastic** [comment]
same thing happened to. me fps normal when i look away. but then crashes anyway

**Comment by mrsterner** [comment]
fixed in 0.1.3
